#spring:
#  datasource:
#    #type: com.alibaba.druid.pool.DruidDataSource
#    #MySQL配置
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.98.34.187:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 47.98.34.187:8848
#        password: nacos
#        username: nacos
#    gateway:
#      routes:
#        - id: product_route
#          uri: lb://gulimall-product
#          predicates:
#            - Path=/api/product/**,/hello
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
#        - id: member_route
#          uri: lb://gulimall-member
#          predicates:
#            - Path=/api/member/**,/hello
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
#        - id: third_party_route
#          uri: lb://gulimall-third-party
#          predicates:
#            - Path=/api/thirdparty/**
#          filters:
#            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
#        - id: ware_route
#          uri: lb://gulimall-ware
#          predicates:
#            - Path=/api/ware/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
#        #没有匹配到的，交给后台
#        - id: admin_route
#          uri: lb://renren-fast #负载均衡到哪里
#          predicates: #你的判断依据是：
#            - Path=/api/**
#          filters: #路径重写 下面是！
#            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
#        - id: host_search
#          uri: lb://gulimall-search
#          predicates: #host鉴权search.gulimall.com来的请求都路由到gulimall-search服务
#            - Host=search.gulimall.com
#        - id: host_auth
#          uri: lb://gulimall-auth
#          predicates: #host鉴权auth.gulimall.com来的请求都路由到gulimall-auth服务
#            - Host=auth.gulimall.com
#        - id: host_cart
#          uri: lb://gulimall-cart
#          predicates: #host鉴权cart.gulimall.com来的请求都路由到gulimall-cart服务
#            - Host=cart.gulimall.com
#        - id: host_route
#          uri: lb://gulimall-product
#          predicates: #host鉴权**.gulimall.com来的请求都路由到gulimall-product服务
#            - Host=gulimall.com,item.gulimall.com
#
#  application:
#    name: gulimall-gateway
#
#mybatis-plus:
#  mapperLocations: classpath:mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#server:
#  port: 88