spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.34.187:8848
        password: nacos
        username: nacos
          # username
          #spring.cloud.nacos.config.server-addr=47.98.34.187:8848
          #spring.cloud.nacos.config.username=nacos
          #spring.cloud.nacos.config.password=nacos
        #spring.cloud.nacos.config.namespace=1000
        #spring.cloud.nacos.config.refresh.enabled=true
      config:
        server-addr:  47.98.34.187:8848
        enabled: true
        password: nacos
        username: nacos
  application:
    name: gulimall-third-party
server:
  port: 30000
alibaba:
  cloud:
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key: LTAI5tRttyYj5cJuWPRG1ktA
    secret-key: dw6clEGxoEuWTX2QmdB6RCdTjQjJL2
    bucket: suxiuwei