spring:
  thymeleaf:
    cache: false
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: true
# 自定义线程池参数
gulimall:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300