CREATE DATABASE IF NOT EXISTS gulimall_oms DEFAULT CHARACTER SET utf8   -> DEFAULT COLLATE utf8_chinese_ci;
CREATE DATABASE IF NOT EXISTS gulimall_pms DEFAULT CHARACTER SET utf8   -> DEFAULT COLLATE utf8_chinese_ci;
CREATE DATABASE IF NOT EXISTS gulimall_sms DEFAULT CHARACTER SET utf8   -> DEFAULT COLLATE utf8_chinese_ci;
CREATE DATABASE IF NOT EXISTS gulimall_ums DEFAULT CHARACTER SET utf8   -> DEFAULT COLLATE utf8_chinese_ci;
CREATE DATABASE IF NOT EXISTS gulimall_wms DEFAULT CHARACTER SET utf8   -> DEFAULT COLLATE utf8_chinese_ci;
CREATE DATABASE IF NOT EXISTS pms_catelog DEFAULT CHARACTER SET utf8   -> DEFAULT COLLATE utf8_chinese_ci;
